-- 31/07/2013 02:17:10 PM VET
-- LVE Withholding
CREATE TABLE LVE_PersonType (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, LVE_PersonType_ID NUMBER(10) NOT NULL, Name NVARCHAR2(60) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT LVE_PersonType_Key PRIMARY KEY (LVE_PersonType_ID))
;

-- 31/07/2013 02:17:23 PM VET
-- LVE Withholding
CREATE TABLE LVE_TaxUnit (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, LVE_TaxUnit_ID NUMBER(10) NOT NULL, Name NVARCHAR2(60) NOT NULL, Processing CHAR(1) DEFAULT NULL , TaxAmt NUMBER NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, ValidFrom DATE NOT NULL, CONSTRAINT LVE_TaxUnit_Key PRIMARY KEY (LVE_TaxUnit_ID))
;

-- 31/07/2013 02:17:32 PM VET
-- LVE Withholding
CREATE TABLE LVE_WC_ProductCharge (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, C_Charge_ID NUMBER(10) DEFAULT NULL , Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, LVE_WC_ProductCharge_ID NUMBER(10) NOT NULL, LVE_WithholdingConcept_ID NUMBER(10) NOT NULL, M_Product_ID NUMBER(10) DEFAULT NULL , Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT LVE_WC_ProductCharge_Key PRIMARY KEY (LVE_WC_ProductCharge_ID))
;

-- 31/07/2013 02:17:46 PM VET
-- LVE Withholding
CREATE TABLE LVE_WH_Conbination (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Aliquot NUMBER NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, LVE_PersonType_ID NUMBER(10) DEFAULT NULL , LVE_WH_Conbination_ID NUMBER(10) NOT NULL, LVE_WithholdingConcept_ID NUMBER(10) NOT NULL, Processing CHAR(1) DEFAULT NULL , Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, Value NVARCHAR2(60) DEFAULT NULL , CONSTRAINT LVE_WH_Conbination_Key PRIMARY KEY (LVE_WH_Conbination_ID))
;

-- 31/07/2013 02:17:52 PM VET
-- LVE Withholding
CREATE TABLE LVE_Withholding (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Beneficiary VARCHAR2(10) NOT NULL, C_Charge_ID NUMBER(10) NOT NULL, Classname NVARCHAR2(255) DEFAULT NULL , Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, DeclarationDocType VARCHAR2(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsSOTrx CHAR(1) DEFAULT 'N' CHECK (IsSOTrx IN ('Y','N')), LVE_Withholding_ID NUMBER(10) NOT NULL, LVE_WithholdingType_ID NUMBER(10) NOT NULL, Name NVARCHAR2(60) NOT NULL, TaxUnitRate NUMBER DEFAULT NULL , Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, WithholdingDocType VARCHAR2(10) NOT NULL, CONSTRAINT LVE_Withholding_Key PRIMARY KEY (LVE_Withholding_ID))
;

-- 31/07/2013 02:19:00 PM VET
-- LVE Withholding
CREATE TABLE LVE_WithholdingConcept (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, LVE_Withholding_ID NUMBER(10) NOT NULL, LVE_WithholdingConcept_ID NUMBER(10) NOT NULL, Name NVARCHAR2(255) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT LVE_WithholdingConcept_Key PRIMARY KEY (LVE_WithholdingConcept_ID))
;

-- 31/07/2013 02:19:07 PM VET
-- LVE Withholding
CREATE TABLE LVE_WithholdingConfig (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, LVE_TaxUnit_ID NUMBER(10) NOT NULL, LVE_WH_Conbination_ID NUMBER(10) NOT NULL, LVE_WithholdingConfig_ID NUMBER(10) NOT NULL, MinimalAmt NUMBER NOT NULL, Subtrahend NUMBER NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT LVE_WithholdingConfig_Key PRIMARY KEY (LVE_WithholdingConfig_ID))
;

-- 31/07/2013 02:19:13 PM VET
-- LVE Withholding
CREATE TABLE LVE_WithholdingRelation (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, C_BP_Group_ID NUMBER(10) DEFAULT NULL , C_BPartner_ID NUMBER(10) DEFAULT NULL , C_DocType_ID NUMBER(10) DEFAULT NULL , Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, LVE_Withholding_ID NUMBER(10) NOT NULL, LVE_WithholdingRelation_ID NUMBER(10) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT LVE_WithholdingRelation_Key PRIMARY KEY (LVE_WithholdingRelation_ID))
;

-- 31/07/2013 02:19:22 PM VET
-- LVE Withholding
CREATE TABLE LVE_WithholdingType (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, LVE_WithholdingType_ID NUMBER(10) NOT NULL, Name NVARCHAR2(60) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, Value NVARCHAR2(60) DEFAULT NULL , CONSTRAINT LVE_WithholdingType_Key PRIMARY KEY (LVE_WithholdingType_ID))
;

-- 31/07/2013 02:22:36 PM VET
-- LVE Withholding
ALTER TABLE C_BPartner ADD LVE_PersonType_ID NUMBER(10) DEFAULT NULL 
;

-- 31/07/2013 02:23:07 PM VET
-- LVE Withholding
ALTER TABLE C_Invoice ADD LVE_WithholdingConcept_ID NUMBER(10) DEFAULT NULL 
;

-- 31/07/2013 02:23:31 PM VET
-- LVE Withholding
ALTER TABLE C_InvoiceLine ADD DocAffected VARCHAR2(10) DEFAULT NULL 
;

-- 31/07/2013 02:23:45 PM VET
-- LVE Withholding
ALTER TABLE C_InvoiceLine ADD LVE_WithholdingConfig_ID NUMBER(10) DEFAULT NULL 
;


