-- Aug 10, 2013 1:58:57 PM VET
-- LVE Withholding
ALTER TABLE C_Invoice ADD COLUMN LVE_WH_Concept_ID NUMERIC(10) DEFAULT NULL 
;

-- Aug 10, 2013 2:00:41 PM VET
-- LVE Withholding
ALTER TABLE C_InvoiceLine ADD COLUMN DocAffected_ID NUMERIC(10) DEFAULT NULL 
;

-- Aug 10, 2013 2:00:57 PM VET
-- LVE Withholding
ALTER TABLE C_InvoiceLine ADD COLUMN LVE_WH_Config_ID NUMERIC(10) DEFAULT NULL 
;

-- Aug 10, 2013 2:01:21 PM VET
-- LVE Withholding
ALTER TABLE C_BPartner ADD COLUMN LVE_PersonType_ID NUMERIC(10) DEFAULT NULL 
;

-- Aug 10, 2013 2:40:55 PM VET
-- LVE Withholding
ALTER TABLE C_DocType ADD COLUMN DocTypeDeclare VARCHAR(2) DEFAULT NULL 
;

-- Aug 13, 2013 8:08:03 AM VET
-- LVE Withholding
ALTER TABLE C_Invoice ADD COLUMN ControlNo VARCHAR(60) DEFAULT NULL 
;

